#!/usr/bin/env bash
set -e

tags="$1"

if [ -z $tags ]; then
  tags="all"
fi

if ! [ -x "$(command -v ansible)" ]; then
  sudo apt install software-properties-common
  sudo add-apt-repository --yes --update ppa:ansible/testing-ansible-2.10
  sudo apt update
  sudo apt install ansible
fi

ansible-playbook -i ~/.dotfiles/hosts ~/.dotfiles/dotfiles.yaml --ask-become-pass --tags $tags

if command -v terminal-notifier 1>/dev/null 2>&1; then
  terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up local env."
fi
