- name: Setup local workstation
  hosts: local
  roles:
    - role: apt
      tags:
        - apt
    - role: git
      tags:
        - git
    - role: rust
      tags:
        - rust
    - role: tmux
      tags:
        - tmux
    - role: nerdfonts
      tags:
        - nerdfonts
    - role: alacritty
      tags:
        - alacritty
    - role: asdf
      tags:
        - asdf
    - role: golang
      tags:
        - golang
    - role: python
      tags:
        - python
    - role: node
      tags:
        - node
    - role: terraform
      tags:
        - terraform
    - role: vim
      tags:
        - vim
    - role: zsh
      tags:
        - zsh
