- name: Setup local workstation
  hosts: local
  roles:
    - role: apt
      tags:
        - apt
    - role: git
      tags:
        - git
    - role: tmux
      tags:
        - tmux
    - role: asdf
      tags:
        - asdf
    - role: golang
      tags:
        - golang
