- name: Add python plugin for asdf
  command: asdf plugin-add python
  register: python_add
  failed_when: python_add == 1

- name: Install python3 {{python3_version}} with asdf"
  command: "asdf install python {{python3_version}}"

- name: Install python3 {{python2_version}} with asdf"
  command: "asdf install python {{python2_version}}"

- name: Set global versions for python
  command: "asdf global python {{python3_version}} {{python2_version}}"
