# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 150
    lines: 50
  padding:
    x: 10
    y: 10
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 0.95

font:
  normal:
    family: Dank Mono
    style: Regular

  # The bold font face
  bold:
    family: Dank Mono
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Dank Mono
    # Style can be specified to pick a specific face.
    style: Italic

  size: 14.0
