- name: Install git
  apt: name=git state=present
  become: yes
  become_user: root
  become_method: sudo

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes

- name: Check if gitconfig exists
  stat: path="{{dotfiles_user_home}}/.gitconfig"
  register: gitconfig_stat

- name: Link GitConfig
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitconfig"
    dest: "{{dotfiles_user_home}}/.gitconfig"
    state: link
    force: yes
