- name: Add nodejs plugin to asdf
  command: "asdf plugin-add nodejs"
  register: node_add
  failed_when: node_add == 2

- name: Import OpenPGP key
  command: "bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring"

- name: Install nodejs {{current_node_version}} with asdf
  command: asdf install nodejs {{current_node_version}}

- name: Install nodejs {{lts_node_version}} with asdf
  command: asdf install nodejs {{lts_node_version}}

- name: Set global version for nodejs to {{current_node_version}}
  command: "asdf global nodejs {{current_node_version}}"

- name: Install "yarn" node.js package globally
  npm:
    name: yarn
    global: yes
