- name: Ensure workspace src directory
  file:
    path: "{{ source_code_path }}"
    state: directory

- name: Checkout source code
  git:
    repo: "{{ alacritty_repo }}"
    dest: "{{ source_code_path }}"
    update: yes
    clone: yes

- name: Check for existing Alacritty release
  stat:
    path: "{{ source_code_path }}/{{ target_path }}"
  register: alacritty_release

- name: Build Alacritty release
  command: cargo build --release
  args:
    chdir: "{{ source_code_path }}"
  when: alacritty_release.stat.exists == false

- name: Install Alacritty binary
  command: cp "{{source_code_path }}/{{ target_path }}" "/usr/local/bin"
  become: yes
  become_user: root
  become_method: sudo

- name: Install Alacritty logo
  command: cp "{{source_code_path }}/extra/logo/alacritty-term.svg" "/usr/share/pixmaps/Alacritty.svg"
  become: yes
  become_user: root
  become_method: sudo

- name: Install Alacritty desktop-file-install
  command: desktop-file-install  "{{source_code_path}}/extra/linux/Alacritty.desktop"
  become: yes
  become_user: root
  become_method: sudo

- name: Update desktop database
  command: update-desktop-database
  become: yes
  become_user: root
  become_method: sudo

- name: Setup TermInfo
  command: tic -xe alacritty,alacritty-direct "{{source_code_path}}/extra/alacritty.info"
  become: yes
  become_user: root
  become_method: sudo


- name: Ensure config directory
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Symlink Alacritty config
  file:
    src: "{{ dotfiles_home }}/roles/alacritty/files/alacritty.yml"
    dest: "{{ config_dir }}/alacritty.yml"
    state: link
